[package]
name = "new_faulhaber"
version = "0.1"
lean_version = "leanprover-community/lean:3.26.0"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "2411d681127e17b7ba96b80c50c9e50f631491da"}
lean-gptf = {git = "https://github.com/jesse-michael-han/lean-gptf", rev = "3e20785d65604744e9e2dc9d710a695a7355fd2c"}
